
/*------------------------------------------------------------------------
    File        : ILogger
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Sat Apr 09 14:45:58 CEST 2016
    Notes       : 
  ----------------------------------------------------------------------*/


interface bfv.sys.log.ILogger:  
  
  method public void Log(logText as character).
  
end interface.